plugins:
  - module: Filter::Request::ServeCache
    config:
      content_type: image/*

  - module: Filter::Request::BasicAuth
    config:
      username: username
      password: password

  - module: Filter::Response::Store
  - module: Filter::Response::FetchLinks
  - module: Filter::Response::ServeCacheOn404

logger:
  - module: Screen
    config:
      min_level: debug
  - module: File
    config:
      min_level: info
      filename: log/modoi.log
