plugins:
  - module: Filter::Request::BasicAuth
    config:
      username: username
      password: password

  - module: Filter::ServeCache
    config:
      content_type: image/*

  - module: Filter::Response::Prefetch

  - module: Filter::Fetcher::Store
    config:
      regexp:
        - 2chan.net(?::\d+)?/\w+/(?:src|res|thumb)/
        - www.nijibox5.com/futabafiles/tubu/src/

  - module: Filter::Fetcher::Script

server:
  name: modoi
  engine:
    port: 3128

logger:
  - module: Screen
    config:
      min_level: debug
  - module: File
    config:
      min_level: info
      filename: log/modoi.log
