Modoi:
  components:
    - Cache
    - UseBrowserCache
    - StoreDB
#   - Watch
#   - IndexEstraier

# below are default config

# Component::Cache:
#   cache_root: .cache
#   override_not_found: yes
# 
# Component::IndexEstraier:
#   node_url: http://localhost:1978/node/modoi
#   node_user: admin
#   node_password: admin
