server:
  port: 3128
  middlewares:
   - module: ModuleReload
fetcher:
  cache:
    module: Cache::FileCache
    args:
      cache_root: .cache
  serve_cache:
    content_type: image/*
  save_thread:
    host: '*.2chan.net'
    path: /res/\d+\.htm$
watcher:
  watch:
    host: '*.2chan.net'
    path: /res/\d+\.htm$
logger:
  screen:
    min_level: debug
